packages:
  - playground
  - examples/*
  - packages/*
  - '!**/test/**'
  - docs
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@iconify-json/carbon': ^1.2.3
  '@iconify-json/fluent-emoji': ^1.2.1
  '@iconify-json/lets-icons': ^1.2.1
  '@iconify-json/line-md': ^1.2.2
  '@iconify-json/logos': ^1.2.3
  '@iconify-json/ri': ^1.2.2
  '@shikijs/vitepress-twoslash': ^1.22.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.7.9
  '@types/prettier': ^3.0.0
  '@unocss/cli': ^0.63.6
  '@unocss/preset-attributify': ^0.63.6
  '@unocss/preset-icons': ^0.63.6
  '@unocss/preset-mini': ^0.63.6
  '@unocss/preset-uno': ^0.63.6
  '@unocss/preset-web-fonts': ^0.63.6
  '@unocss/reset': ^0.63.6
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vitest/coverage-c8': ^0.33.0
  '@vitest/ui': ^2.1.3
  '@vue/repl': ^4.4.2
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^11.1.0
  bumpp: ^9.7.1
  compare-versions: ^6.1.1
  cross-env: ^7.0.3
  eslint: ^9.13.0
  esno: ^4.8.0
  execa: ^9.4.1
  floating-vue: ^5.2.2
  fs-extra: ^11.2.0
  jsdom: ^25.0.1
  lint-staged: ^15.2.10
  magic-color: ^2.0.0
  npm-run-all: ^4.1.5
  ohmyfetch: ^0.4.21
  prettier: ^3.3.3
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.17.2
  tsup: ^8.3.0
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unocss: ^0.63.6
  unocss-transformer-alias: ^0.0.8
  unplugin-auto-import: ^0.18.3
  unplugin-vue-components: ^0.27.4
  vite: ^5.4.10
  vite-plugin-dts: 4.0.3
  vite-plugin-inspect: ^0.8.7
  vitepress: ^1.4.1
  vitest: ^2.1.3
  vue: ^3.5.12
  vue-tsc: ^2.1.6
