packages:
  - playground
  - examples/*
  - packages/*
  - '!**/test/**'
  - docs
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@iconify-json/carbon': ^1.2.7
  '@iconify-json/fluent-emoji': ^1.2.3
  '@iconify-json/lets-icons': ^1.2.1
  '@iconify-json/line-md': ^1.2.5
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@shikijs/vitepress-twoslash': ^3.0.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.13.5
  '@types/prettier': ^3.0.0
  '@unocss/cli': ^66.1.0-beta.1
  '@unocss/preset-attributify': ^66.1.0-beta.1
  '@unocss/preset-icons': ^66.1.0-beta.1
  '@unocss/preset-mini': ^66.1.0-beta.1
  '@unocss/preset-uno': ^66.1.0-beta.1
  '@unocss/preset-web-fonts': ^66.1.0-beta.1
  '@unocss/reset': ^66.1.0-beta.2
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-c8': ^0.33.0
  '@vitest/ui': ^3.0.7
  '@vue/repl': ^4.5.1
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^12.7.0
  bumpp: ^10.0.3
  compare-versions: ^6.1.1
  cross-env: ^7.0.3
  eslint: ^9.21.0
  esno: ^4.8.0
  execa: ^9.5.2
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  jsdom: ^26.0.0
  lint-staged: ^15.4.3
  magic-color: ^2.0.1
  npm-run-all: ^4.1.5
  ohmyfetch: ^0.4.21
  prettier: ^3.5.2
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^18.6.0
  tsup: ^8.4.0
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^66.1.0-beta.1
  unocss-transformer-alias: ^0.0.8
  unplugin-auto-import: ^19.1.0
  unplugin-vue-components: ^28.4.0
  vite: ^6.2.0
  vite-plugin-dts: 4.0.3
  vite-plugin-inspect: ^11.0.0
  vitepress: ^1.6.3
  vitest: ^3.0.7
  vue: ^3.5.13
  vue-flow-layout: ^0.1.1
  vue-tsc: ^2.2.4
