packages:
  - playground
  - examples/*
  - packages/*
  - '!**/test/**'
  - docs

catalogs:
  # UnoCSS ecosystem
  unocss:
    '@unocss/cli': ^66.5.4
    '@unocss/preset-attributify': ^66.5.4
    '@unocss/preset-icons': ^66.5.4
    '@unocss/preset-uno': ^66.5.4
    '@unocss/preset-web-fonts': ^66.5.4
    '@unocss/preset-wind4': ^66.5.4
    '@unocss/reset': ^66.5.4
    'magic-color': ^2.0.3
    'unocss': ^66.5.4
    'unocss-transformer-alias': ^0.0.8
  
  # Vue ecosystem
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    '@vue/repl': ^4.7.0
    '@vue/test-utils': ^2.4.6
    '@vueuse/core': ^13.9.0
    'floating-vue': ^5.2.2
    'vue': ^3.5.22
    'vue-flow-layout': ^0.2.0
    'vue-tsc': ^3.1.1
  
  # Build tools
  build:
    'tsup': ^8.5.0
    'typescript': ^5.9.3
    'unbuild': ^3.6.1
    'unplugin-auto-import': ^20.2.0
    'unplugin-vue-components': ^30.0.0
    'vite': ^7.1.11
    'vite-plugin-dts': 4.0.3
    'vite-plugin-inspect': ^11.3.3
  
  # Testing
  testing:
    '@vitest/coverage-c8': ^0.33.0
    '@vitest/ui': ^3.2.4
    'jsdom': ^27.0.1
    'vitest': ^3.2.4
  
  # Documentation
  docs:
    '@shikijs/vitepress-twoslash': ^3.13.0
    'vitepress': ^1.6.4
  
  # Icon libraries
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/fluent-emoji': ^1.2.6
    '@iconify-json/lets-icons': ^1.2.1
    '@iconify-json/line-md': ^1.2.11
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.6
  
  # Development tools
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.9.1
    '@types/prettier': ^3.0.0
    'bumpp': ^10.3.1
    'compare-versions': ^6.1.1
    'cross-env': ^10.1.0
    'eslint': ^9.38.0
    'esno': ^4.8.0
    'execa': ^9.6.0
    'fs-extra': ^11.3.2
    'lint-staged': ^16.2.5
    'npm-run-all': ^4.1.5
    'ohmyfetch': ^0.4.21
    'prettier': ^3.6.2
    'rimraf': ^6.0.1
    'simple-git-hooks': ^2.13.1
    'taze': ^19.8.1
