packages:
  - playground
  - examples/*
  - packages/*
  - '!**/test/**'
  - docs
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/fluent-emoji': ^1.2.2
  '@iconify-json/lets-icons': ^1.2.1
  '@iconify-json/line-md': ^1.2.4
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@shikijs/vitepress-twoslash': ^1.24.4
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.10.2
  '@types/prettier': ^3.0.0
  '@unocss/cli': ^0.65.3
  '@unocss/preset-attributify': ^0.65.3
  '@unocss/preset-icons': ^0.65.3
  '@unocss/preset-mini': ^0.65.3
  '@unocss/preset-uno': ^0.65.3
  '@unocss/preset-web-fonts': ^0.65.3
  '@unocss/reset': ^0.65.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-c8': ^0.33.0
  '@vitest/ui': ^2.1.8
  '@vue/repl': ^4.4.2
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^12.2.0
  bumpp: ^9.9.2
  compare-versions: ^6.1.1
  cross-env: ^7.0.3
  eslint: ^9.17.0
  esno: ^4.8.0
  execa: ^9.5.2
  floating-vue: ^5.2.2
  fs-extra: ^11.2.0
  jsdom: ^25.0.1
  lint-staged: ^15.2.11
  magic-color: ^2.0.0
  npm-run-all: ^4.1.5
  ohmyfetch: ^0.4.21
  prettier: ^3.4.2
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  tsup: ^8.3.5
  typescript: ^5.7.2
  unbuild: ^3.0.1
  unocss: ^0.65.3
  unocss-transformer-alias: ^0.0.8
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.28.0
  vite: ^6.0.6
  vite-plugin-dts: 4.0.3
  vite-plugin-inspect: ^0.10.6
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-flow-layout: ^0.1.1
  vue-tsc: ^2.2.0
