/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header.vue')['default']
  }
}

// For TSX support
declare global {
  const Header: typeof import('./components/Header.vue')['default']
}