// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bg: typeof import('./components/Bg.vue')['default']
    OAlert: typeof import('onu-ui/components')['OAlert']
    OAvatar: typeof import('onu-ui/components')['OAvatar']
    OAvatarGroup: typeof import('onu-ui/components')['OAvatarGroup']
    OBadge: typeof import('onu-ui/components')['OBadge']
    OButton: typeof import('onu-ui/components')['OButton']
    OCard: typeof import('onu-ui/components')['OCard']
    OCheckbox: typeof import('onu-ui/components')['OCheckbox']
    OCollapse: typeof import('onu-ui/components')['OCollapse']
    OCollapseItem: typeof import('onu-ui/components')['OCollapseItem']
    OIcon: typeof import('onu-ui/components')['OIcon']
    OPopup: typeof import('onu-ui/components')['OPopup']
    ORate: typeof import('onu-ui/components')['ORate']
    OSwitch: typeof import('onu-ui/components')['OSwitch']
    OTag: typeof import('onu-ui/components')['OTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAlert: typeof import('./components/TheAlert.vue')['default']
    TheAvatar: typeof import('./components/TheAvatar.vue')['default']
    TheBadge: typeof import('./components/TheBadge.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCard: typeof import('./components/TheCard.vue')['default']
    TheCheckbox: typeof import('./components/TheCheckbox.vue')['default']
    TheCollapse: typeof import('./components/TheCollapse.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheIcon: typeof import('./components/TheIcon.vue')['default']
    TheMessage: typeof import('./components/TheMessage.vue')['default']
    ThePopup: typeof import('./components/ThePopup.vue')['default']
    TheRate: typeof import('./components/TheRate.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheTag: typeof import('./components/TheTag.vue')['default']
  }
}
