// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bg: typeof import('./components/Bg.vue')['default']
    OAlert: typeof import('onu-ui')['OAlert']
    OAvatar: typeof import('onu-ui')['OAvatar']
    OAvatarGroup: typeof import('onu-ui')['OAvatarGroup']
    OBadge: typeof import('onu-ui')['OBadge']
    OButton: typeof import('onu-ui')['OButton']
    OCard: typeof import('onu-ui')['OCard']
    OCheckbox: typeof import('onu-ui')['OCheckbox']
    OIcon: typeof import('onu-ui')['OIcon']
    OPopup: typeof import('onu-ui')['OPopup']
    OSwitch: typeof import('onu-ui')['OSwitch']
    OTag: typeof import('onu-ui')['OTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAlert: typeof import('./components/TheAlert.vue')['default']
    TheAvatar: typeof import('./components/TheAvatar.vue')['default']
    TheBadge: typeof import('./components/TheBadge.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCard: typeof import('./components/TheCard.vue')['default']
    TheCheckbox: typeof import('./components/TheCheckbox.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheIcon: typeof import('./components/TheIcon.vue')['default']
    TheMessage: typeof import('./components/TheMessage.vue')['default']
    ThePopup: typeof import('./components/ThePopup.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheTag: typeof import('./components/TheTag.vue')['default']
  }
}
