---
name: Bug report
about: Please describe your problems in detail
title: BUG
labels: bug
---

**Describe the bug**
A clear and concise description of what the bug is.

**To reproduce a behavior**

1. To...
2. On click...
3. ....
4. Errors found

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version environment**
Please describe the circumstances in which you made errors, such as:

- onu-ui: `0.0.1`
- Vue: `3.0.0`
- browser: xxx

**Additional context**
Add any other context about the problem here.
