export const cardShortcuts: Record<string, string> = {
  // card
  'o-card-base': 'o-transition list-none relative rounded-md text-baseText w-full of-hidden',
  'o-card': 'o-card-base h-fit bg-lightBackground dark:border dark:b-lightBorder',
  'o-card-md': 'rounded-md text-sm',
  'o-card-sm': 'rounded-sm text-xs',
  'o-card-cover': 'children-w-full children-aspect-video',
  'o-card-header': 'fb px-4 py-2.5',
  'o-card-header-wrapper': 'flex flex-col flex-1 gap-1.5',
  'o-card-header-title': 'text-title font-medium',
  'o-card-header-description': 'text-xs text-darkSubText break-all !m-0',
  'o-card-header-extra': 'absolute right-4 top-2.5',
  'o-card-body': 'p-4 pt-1.5 leading-normal text-sm dark:c-darkText',
  'o-card-actions': 'p-4 pt-2',
  'o-card-bordered': 'border b-lightBorder important-shadow-none',
  'o-card-hoverable': 'border b-lightBorder hover-translate-y--1 hover-important-shadow-cardMD',
  'o-card-shadow-always': '!shadow-cardMD',
  'o-card-shadow-never': 'shadow-none border b-lightBorder',
  'o-card-embed': 'bg-embed dark:bg-lightBackground',
}
