/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    OAvatar: typeof import('./components/o-avatar.vue')['default']
    OBadge: typeof import('./components/o-badge.vue')['default']
    OButton: typeof import('./components/o-button.vue')['default']
    OCard: typeof import('./components/o-card.vue')['default']
    OCheckbox: typeof import('./components/o-checkbox.vue')['default']
    OInput: typeof import('./components/o-input.vue')['default']
    ORadio: typeof import('./components/o-radio.vue')['default']
    OSwitch: typeof import('./components/o-switch.vue')['default']
  }
}

// For TSX support
declare global {
  const OAvatar: typeof import('./components/o-avatar.vue')['default']
  const OBadge: typeof import('./components/o-badge.vue')['default']
  const OButton: typeof import('./components/o-button.vue')['default']
  const OCard: typeof import('./components/o-card.vue')['default']
  const OCheckbox: typeof import('./components/o-checkbox.vue')['default']
  const OInput: typeof import('./components/o-input.vue')['default']
  const ORadio: typeof import('./components/o-radio.vue')['default']
  const OSwitch: typeof import('./components/o-switch.vue')['default']
}