/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bg: typeof import('./components/Bg.vue')['default']
    OAlert: typeof import('onu-ui')['OAlert']
    OAvatar: typeof import('onu-ui')['OAvatar']
    OAvatarGroup: typeof import('onu-ui')['OAvatarGroup']
    OBadge: typeof import('onu-ui')['OBadge']
    OButton: typeof import('onu-ui')['OButton']
    OCard: typeof import('onu-ui')['OCard']
    OCheckbox: typeof import('onu-ui')['OCheckbox']
    OCollapse: typeof import('onu-ui')['OCollapse']
    OCollapseItem: typeof import('onu-ui')['OCollapseItem']
    OIcon: typeof import('onu-ui')['OIcon']
    OPopup: typeof import('onu-ui')['OPopup']
    ORate: typeof import('onu-ui')['ORate']
    OSwitch: typeof import('onu-ui')['OSwitch']
    OTag: typeof import('onu-ui')['OTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAffix: typeof import('./components/TheAffix.vue')['default']
    TheAlert: typeof import('./components/TheAlert.vue')['default']
    TheAvatar: typeof import('./components/TheAvatar.vue')['default']
    TheBacktop: typeof import('./components/TheBacktop.vue')['default']
    TheBadge: typeof import('./components/TheBadge.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCard: typeof import('./components/TheCard.vue')['default']
    TheCheckbox: typeof import('./components/TheCheckbox.vue')['default']
    TheCollapse: typeof import('./components/TheCollapse.vue')['default']
    TheEmpty: typeof import('./components/TheEmpty.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheIcon: typeof import('./components/TheIcon.vue')['default']
    TheLink: typeof import('./components/TheLink.vue')['default']
    TheMessage: typeof import('./components/TheMessage.vue')['default']
    ThePopup: typeof import('./components/ThePopup.vue')['default']
    TheProgress: typeof import('./components/TheProgress.vue')['default']
    TheRadio: typeof import('./components/TheRadio.vue')['default']
    TheRate: typeof import('./components/TheRate.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheTag: typeof import('./components/TheTag.vue')['default']
    TheText: typeof import('./components/TheText.vue')['default']
    TheToolTip: typeof import('./components/TheToolTip.vue')['default']
  }
}
