// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bg: typeof import('./components/Bg.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    OAvatar: typeof import('onu-ui')['OAvatar']
    OButton: typeof import('onu-ui')['OButton']
    OIcon: typeof import('onu-ui')['OIcon']
    TheAvatar: typeof import('./components/TheAvatar.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheIcon: typeof import('./components/TheIcon.vue')['default']
  }
}

export {}
