/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Feature: typeof import('./.vitepress/theme/components/Feature.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    Overview: typeof import('./.vitepress/theme/components/Overview.vue')['default']
    ThemePalette: typeof import('./.vitepress/theme/components/ThemePalette.vue')['default']
    ThemePaletteInner: typeof import('./.vitepress/theme/components/ThemePaletteInner.vue')['default']
  }
}

// For TSX support
declare global {
  const Feature: typeof import('./.vitepress/theme/components/Feature.vue')['default']
  const HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
  const Overview: typeof import('./.vitepress/theme/components/Overview.vue')['default']
  const ThemePalette: typeof import('./.vitepress/theme/components/ThemePalette.vue')['default']
  const ThemePaletteInner: typeof import('./.vitepress/theme/components/ThemePaletteInner.vue')['default']
}