/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Feature: typeof import('./.vitepress/theme/components/Feature.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    Overview: typeof import('./.vitepress/theme/components/Overview.vue')['default']
    ThemePalette: typeof import('./.vitepress/theme/components/ThemePalette.vue')['default']
    ThemePaletteInner: typeof import('./.vitepress/theme/components/ThemePaletteInner.vue')['default']
  }
}
